Configured Strelka and added multi-threading support to Mutect2

diff --git a/src/command_meta/call_somatic_variants_strelka.yaml b/src/command_meta/call_somatic_variants_strelka.yaml
--- a/src/command_meta/call_somatic_variants_strelka.yaml
+++ b/src/command_meta/call_somatic_variants_strelka.yaml
@@ -1,12 +1,57 @@
 description: Calls somatic variants using Strelka for a tumor/normal pair.
 args:
-    - TEMP:
-        default: ""
-        opts: ""
-        description: ""
+    - REF_GENOME:
+        default: "Null"
+        opts: "-r | --reference"
+        description: "Name of the reference genome FASTA file."
         required: True
-        example: ""
+        example: "-r hg19.fa"
+    - TUMOR:
+        default: "Null"
+        opts: "-t | --tumor"
+        description: "Path to a BAM file with tumor data."
+        required: True
+        example: "-t SampleA_Tumor.bam"
+    - NORMAL:
+        default: "Null"
+        opts: "-n | --normal"
+        description: "Path to a BAM file with normal data."
+        required: True
+        example: "-n SampleA_Normal.bam"
+    - INDEL:
+        default: ""
+        opts: "-i | --indel_candidates"
+        description: "The Strelka documentation recommends to provide indel candidates from the Manta SV and indel caller to improve sensitivity to call indels of size 20 or larger. You may specify the name of a VCF file with these candidates."
+        required: False
+        example: "-i candidateSmallIndels.vcf.gz"
+    - CALL_REGIONS:
+        default: ""
+        opts: "-c, --call_regions"
+        description: "The Strelka documentation recommends that for references with many short contigs, to provide callable regions to avoid possible runtime issues. You may specified the name of a BED file containing genomic regions to call."
+        required: False
+        example: "-c regions.bed.gz"
+    - EXOME:
+        default: False
+        opts: "-e | --exome"
+        description: "For exome and amplicon sequencing, enable this setting. Acceptable values are True or False."
+        required: False
+        acceptable_values:
+            - False
+            - True
+        example: "--exome True"
+    - THREADS:
+        default: 1
+        opts: "-t | --nthreads"
+        description: "The number of threads that GATK should use."
+        required: False
+        example: "-t 4"
 volumes:
+    - ref_genome:
+        description: "Directory where the reference genome FASTA file is stored."
+        permissions: Read
+    - ref_index:
+        description: "Directory where the index files for the reference genome are stored."
+        permissions: Read
     - bam_files:
         description: "Directory where the BAM file is stored."
         permissions: Read
@@ -14,8 +59,62 @@ volumes:
         description: "Directory where the output file will be stored."
         permissions: ReadWrite
 command_template: |
-    TEMP
+    if [ ! -f /data/bam_files/"${TUMOR}.bai" ] then
+      echo "ERROR: /data/bam_files/\"${TUMOR}.bai\" does not exist. Please run index_bam on /data/bam_files/\"${TUMOR}\"."
+      exit 1;
+    fi
+    if [ ! -f /data/bam_files/"${NORMAL}.bai" ] then
+      echo "ERROR: /data/bam_files/\"${NORMAL}.bai\" does not exist. Please run index_bam on /data/bam_files/\"${NORMAL}\"."
+      exit 1;
+    fi
+
+    ln -s /data/ref_genome/"${REF_GENOME}" /tmp/"${REF_GENOME}"
+
+    INDEX=$(echo "${REF_GENOME}" | grep -o '\.' | grep -c '\.')
+    if [[ "${REF_GENOME: -${INDEX}}" = ".gz" ]]; then
+        NEW_REF="$(echo ${REF_GENOME} | cut -d '.' -f -${INDEX})"
+        gunzip -c /data/ref_genome/"${REF_GENOME}" > /tmp/"${NEW_REF}"
+        REF_GENOME="${NEW_REF}"
+    fi
+
+    NEEDED_FILE=/data/ref_index/"${REF_GENOME}".fai
+
+    if [[ ! -f "${NEEDED_FILE}" ]]; then
+        echo "samtools reference index (${NEEDED_FILE}) is missing."
+        exit 1
+    fi
+
+    ln -s /data/ref_index/"${REF_GENOME}.fai" /tmp/"${REF_GENOME}.fai"
+
+    RUN_DIR="/data/output_data/StrelkaSomaticWorkflow"
+    RUN_DIR_ARG="--runDir=${RUN_DIR}"
+    rm -f "${RUN_DIR_ARG##*=}/runWorkflow.py"
+
+    if [[ "$INDEL" != "" ]]
+    then
+      INDEL="--indelCandidates /data/input_data/$INDEL"
+    fi
+
+    if [[ "$CALL_REGIONS" != "" ]]
+    then
+      CALL_REGIONS="--callRegions /data/input_data/$CALL_REGIONS"
+    fi
+
+    if [[ "$EXOME" == "True" ]]
+    then
+      EXOME="--exome"
+    fi
+
+    #source activate py2.7
+
+    python2.7 /miniconda/envs/py2.7/share/strelka-2.9.10-0/bin/configureStrelkaSomaticWorkflow.py \
+        --referenceFasta=/tmp/"${REF_GENOME}" --tumorBam="/data/bam_files/${TUMOR}" \
+        --normalBam="/data/bam_files/${NORMAL}" ${INDEL} ${CALL_REGIONS} "${RUN_DIR_ARG}" \
+        ${EXOME}
+
+    python2.7 "${RUN_DIR}"/runWorkflow.py -m local -j $THREADS
 receipt_commands: |
     get_bash_version
-    get_python_version
+    get_python2_version
     get_conda_version picard
+    echo "Strelka version 2.9.10-0"
